Updating E-R Model with Seat related entities.
JoseGomez14/sitas-db-model pull request #30
Opened 2024-04-09 21:07 UTC by jgomelop

# Pull Request Template

## Description

Added Seat module related entities. Updated Booking and Passenger entities.

## Checklist

- [x ] My changes adhere to the project's coding standards.
- [x ] I have tested my changes thoroughly.
- [x ] My code is well-documented in README.md.
- [x] I have provided a clear and concise description of my changes in this pull request.

## Tables Modified

### Added Tables:
- [ ] Seat
- [ ] SeatStatus
- [ ] SeatLocation
- [ ] SeatClass

### Modified Tables:
- [ ] Passenger
- [ ] Booking

2024-04-09 21:42 UTC, JoseGomez14 requested changes
Hola!

Estuve revisando y existen algunas incompatibilidades al momento de ejecutar el script con los cambios que han sido introducidos.

- En primer lugar el revisor de sintaxis arroja una advertencia para la siguiente línea:
![image](https://github.com/JoseGomez14/sitas-db-model/assets/110755221/0fb3a79d-46d8-41d6-95da-7959b58f99b4)

- Otro cambio a implementar es el orden en que se ponen las tablas y las referencias (Las referencias solo se pueden hacer a tablas que sean creadas antes de dicha referencia).

Pueden probar en sus bases de datos ejecutando el script completo o herramientas como LiveSQL y actualizar está PR.

2024-04-09 21:53 UTC, daniel-lujan requested changes
Hola!

Además de lo mencionado por Jose, en esta PR se elimina un campo (`passenger_id`) de la tabla `Booking`, perteneciente al módulo de reservas. Nos gustaría conocer el motivo de este cambio y si es concertado con el otro módulo.

Gracias 🤠

2024-04-09 22:40 UTC, jgomelop commented
@JoseGomez14 Hola. Ya realicé las correcciones pertinentes. Tenía una coma demás en Passenger, y al hacer la modificación en los campos de las tablas Passenger y Booking, se me olvidó cambiar el orden. 

Respecto a la pregunta de @daniel-lujan, yo hablé con el módulo de gestión de reservas para realizar dicho cambio en el modelo.  Les presenté el siguiente modelo ER que relaciona nuestro módulo Gestion de Asientos con el de Reservas.

![Copia de Diagrama ER Gestion de Asientos](https://github.com/JoseGomez14/sitas-db-model/assets/67080864/97f96e42-8052-46d8-80e0-85e964f09e37)

Nota: Esta imagen sólo es representativa y no es el modelo exacto como aparece en DB. Lo importante de este modelo es la introducción de una tabla SeatPassenger que nos sirve a nosotros para gestionar la relación entre los asientos y los pasajeros. Es una tabla auxiliar. Por otro lado, el cambio en los campos de las entidades Passenger y Booking lo aprobaron, y de hecho me comentaron que también tenían algo similar, pero que no habían actualizado el script de la base de datos. 

Alguna otra duda me lo hacen saber :)

2024-04-10 00:41 UTC, daniel-lujan approved these changes
✅

2024-04-10 01:26 UTC, JoseGomez14 approved these changes

2024-04-10 01:27 UTC, JoseGomez14 approved these changes
👍

2024-04-10 01:27 UTC, merged